# Generated by Django 3.1.5 on 2021-01-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=3000)),
                ('time', models.DateTimeField(verbose_name='time posted')),
                ('slug', models.CharField(choices=[('/chat-center', '/chat-center'), ('/blog/math-puzzle-jan-11', '/blog/math-puzzle-jan-11'), ('/blog/math-puzzle-mar-29', '/blog/math-puzzle-mar-29'), ('/blog/math-puzzle-jan-18', '/blog/math-puzzle-jan-18'), ('/blog/math-puzzle-may-3', '/blog/math-puzzle-may-3'), ('/blog/math-puzzle-apr-12', '/blog/math-puzzle-apr-12'), ('/blog/math-puzzle-may-17', '/blog/math-puzzle-may-17'), ('/blog/math-puzzle-jan-4', '/blog/math-puzzle-jan-4'), ('/blog/math-puzzle-mar-15', '/blog/math-puzzle-mar-15'), ('/blog/irv-condorcet', '/blog/irv-condorcet'), ('/blog/math-puzzle-apr-26', '/blog/math-puzzle-apr-26'), ('/blog/math-puzzle-feb-8', '/blog/math-puzzle-feb-8'), ('/blog/math-puzzle-mar-22', '/blog/math-puzzle-mar-22'), ('/blog/math-puzzle-mar-1', '/blog/math-puzzle-mar-1'), ('/blog/math-puzzle-feb-15', '/blog/math-puzzle-feb-15'), ('/blog/math-puzzle-feb-1', '/blog/math-puzzle-feb-1')], max_length=1000)),
            ],
        ),
    ]
